# Author: Rubatharisan Thirumathyam
version: "3.7"
services:
  management_service:
    image: management_service:build-${BUILD_NUMBER}
    ports:
      - 18080:8080
    depends_on:
      - rabbitmq
  customer_service:
    image: customer_service:build-${BUILD_NUMBER}
    ports:
      - 18081:8080
    depends_on:
      - rabbitmq
  merchant_service:
    image: merchant_service:build-${BUILD_NUMBER}
    ports:
      - 18082:8080
    depends_on:
      - rabbitmq
  payment_service:
    image: payment_service:build-${BUILD_NUMBER}
    depends_on:
      - rabbitmq
  token_service:
    image: token_service:build-${BUILD_NUMBER}
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - 15672:15672
    volumes:
      - rabbitmq-volume01:/var/lib/rabbitmq
volumes:
  rabbitmq-volume01: {}
