# Author: Rubatharisan Thirumathyam
version: "3.7"
services:
  management_service:
    image: management_service:${BUILD}
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
  customer_service:
    image: customer_service:${BUILD}
    ports:
      - 8081:8080
    depends_on:
      - rabbitmq
  merchant_service:
    image: merchant_service:${BUILD}
    ports:
      - 8082:8080
    depends_on:
      - rabbitmq
  payment_service:
    image: payment_service:${BUILD}
    depends_on:
      - rabbitmq
  token_service:
    image: token_service:${BUILD}
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - 15672:15672
    # volumes:
    #  - rabbitmq-volume01:/var/lib/rabbitmq
volumes:
  rabbitmq-volume01: {}
